export const GET_PACKAGES_START = "GET_PACKAGES_START";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_ERROR = "GET_PACKAGES_ERROR";

export const LOGIN_PROCESSING = "LOGIN_PROCESSING";
export const LOGIN = "LOGIN";

export const PAYMENT_PENDING = "PAYMENT_PENDING";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";